//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProductions.SoftProductionsWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", ConfigurationName="SoftProductionsWebService.SoftProductionsWS")]
    public interface SoftProductionsWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarSeriesXNombre" +
            "Request", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarSeriesXNombre" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWebService.listarSeriesXNombreResponse listarSeriesXNombre(SoftProductions.SoftProductionsWebService.listarSeriesXNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarSeriesXNombre" +
            "Request", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarSeriesXNombre" +
            "Response")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarSeriesXNombreResponse> listarSeriesXNombreAsync(SoftProductions.SoftProductionsWebService.listarSeriesXNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodasProducto" +
            "rasRequest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodasProducto" +
            "rasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWebService.listarTodasProductorasResponse listarTodasProductoras(SoftProductions.SoftProductionsWebService.listarTodasProductorasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodasProducto" +
            "rasRequest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodasProducto" +
            "rasResponse")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarTodasProductorasResponse> listarTodasProductorasAsync(SoftProductions.SoftProductionsWebService.listarTodasProductorasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarDirectoresXNo" +
            "mbreRequest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarDirectoresXNo" +
            "mbreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWebService.listarDirectoresXNombreResponse listarDirectoresXNombre(SoftProductions.SoftProductionsWebService.listarDirectoresXNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarDirectoresXNo" +
            "mbreRequest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarDirectoresXNo" +
            "mbreResponse")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarDirectoresXNombreResponse> listarDirectoresXNombreAsync(SoftProductions.SoftProductionsWebService.listarDirectoresXNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/insertarSerieReques" +
            "t", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/insertarSerieRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWebService.insertarSerieResponse insertarSerie(SoftProductions.SoftProductionsWebService.insertarSerieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/insertarSerieReques" +
            "t", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/insertarSerieRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.insertarSerieResponse> insertarSerieAsync(SoftProductions.SoftProductionsWebService.insertarSerieRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softproductions.pucp.edu.pe/")]
    public partial class serieTelevision : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private capitulo[] capitulosField;
        
        private double costoProduccionField;
        
        private System.DateTime fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private int idSerieTelevisionField;
        
        private ushort idiomaField;
        
        private string nombreSerieField;
        
        private byte[] portadaField;
        
        private productora productoraField;
        
        private string sipnosisField;
        
        private int temporadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("capitulos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public capitulo[] capitulos {
            get {
                return this.capitulosField;
            }
            set {
                this.capitulosField = value;
                this.RaisePropertyChanged("capitulos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double costoProduccion {
            get {
                return this.costoProduccionField;
            }
            set {
                this.costoProduccionField = value;
                this.RaisePropertyChanged("costoProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSerieTelevision {
            get {
                return this.idSerieTelevisionField;
            }
            set {
                this.idSerieTelevisionField = value;
                this.RaisePropertyChanged("idSerieTelevision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreSerie {
            get {
                return this.nombreSerieField;
            }
            set {
                this.nombreSerieField = value;
                this.RaisePropertyChanged("nombreSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public productora productora {
            get {
                return this.productoraField;
            }
            set {
                this.productoraField = value;
                this.RaisePropertyChanged("productora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sipnosis {
            get {
                return this.sipnosisField;
            }
            set {
                this.sipnosisField = value;
                this.RaisePropertyChanged("sipnosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int temporada {
            get {
                return this.temporadaField;
            }
            set {
                this.temporadaField = value;
                this.RaisePropertyChanged("temporada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softproductions.pucp.edu.pe/")]
    public partial class capitulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private director directorField;
        
        private string duracionField;
        
        private int idCapituloField;
        
        private string nombreCapituloField;
        
        private int numeroCapituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public director director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
                this.RaisePropertyChanged("director");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCapitulo {
            get {
                return this.idCapituloField;
            }
            set {
                this.idCapituloField = value;
                this.RaisePropertyChanged("idCapitulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreCapitulo {
            get {
                return this.nombreCapituloField;
            }
            set {
                this.nombreCapituloField = value;
                this.RaisePropertyChanged("nombreCapitulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numeroCapitulo {
            get {
                return this.numeroCapituloField;
            }
            set {
                this.numeroCapituloField = value;
                this.RaisePropertyChanged("numeroCapitulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softproductions.pucp.edu.pe/")]
    public partial class director : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidoDirectorField;
        
        private int idDirectorField;
        
        private string nacionalidadField;
        
        private string nombreDirectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoDirector {
            get {
                return this.apellidoDirectorField;
            }
            set {
                this.apellidoDirectorField = value;
                this.RaisePropertyChanged("apellidoDirector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDirector {
            get {
                return this.idDirectorField;
            }
            set {
                this.idDirectorField = value;
                this.RaisePropertyChanged("idDirector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreDirector {
            get {
                return this.nombreDirectorField;
            }
            set {
                this.nombreDirectorField = value;
                this.RaisePropertyChanged("nombreDirector");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softproductions.pucp.edu.pe/")]
    public partial class productora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private int bField;
        
        private int gField;
        
        private int idProductoraField;
        
        private byte[] logoField;
        
        private string nombreProductoraField;
        
        private int rField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int b {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
                this.RaisePropertyChanged("b");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int g {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
                this.RaisePropertyChanged("g");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProductora {
            get {
                return this.idProductoraField;
            }
            set {
                this.idProductoraField = value;
                this.RaisePropertyChanged("idProductora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
                this.RaisePropertyChanged("logo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreProductora {
            get {
                return this.nombreProductoraField;
            }
            set {
                this.nombreProductoraField = value;
                this.RaisePropertyChanged("nombreProductora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
                this.RaisePropertyChanged("r");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSeriesXNombre", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSeriesXNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarSeriesXNombreRequest() {
        }
        
        public listarSeriesXNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSeriesXNombreResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSeriesXNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWebService.serieTelevision[] @return;
        
        public listarSeriesXNombreResponse() {
        }
        
        public listarSeriesXNombreResponse(SoftProductions.SoftProductionsWebService.serieTelevision[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasProductoras", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasProductorasRequest {
        
        public listarTodasProductorasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasProductorasResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasProductorasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWebService.productora[] @return;
        
        public listarTodasProductorasResponse() {
        }
        
        public listarTodasProductorasResponse(SoftProductions.SoftProductionsWebService.productora[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDirectoresXNombre", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDirectoresXNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarDirectoresXNombreRequest() {
        }
        
        public listarDirectoresXNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDirectoresXNombreResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDirectoresXNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWebService.director[] @return;
        
        public listarDirectoresXNombreResponse() {
        }
        
        public listarDirectoresXNombreResponse(SoftProductions.SoftProductionsWebService.director[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSerie", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSerieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWebService.serieTelevision serie;
        
        public insertarSerieRequest() {
        }
        
        public insertarSerieRequest(SoftProductions.SoftProductionsWebService.serieTelevision serie) {
            this.serie = serie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSerieResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSerieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarSerieResponse() {
        }
        
        public insertarSerieResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoftProductionsWSChannel : SoftProductions.SoftProductionsWebService.SoftProductionsWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoftProductionsWSClient : System.ServiceModel.ClientBase<SoftProductions.SoftProductionsWebService.SoftProductionsWS>, SoftProductions.SoftProductionsWebService.SoftProductionsWS {
        
        public SoftProductionsWSClient() {
        }
        
        public SoftProductionsWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoftProductionsWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoftProductionsWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoftProductionsWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWebService.listarSeriesXNombreResponse SoftProductions.SoftProductionsWebService.SoftProductionsWS.listarSeriesXNombre(SoftProductions.SoftProductionsWebService.listarSeriesXNombreRequest request) {
            return base.Channel.listarSeriesXNombre(request);
        }
        
        public SoftProductions.SoftProductionsWebService.serieTelevision[] listarSeriesXNombre(string nombre) {
            SoftProductions.SoftProductionsWebService.listarSeriesXNombreRequest inValue = new SoftProductions.SoftProductionsWebService.listarSeriesXNombreRequest();
            inValue.nombre = nombre;
            SoftProductions.SoftProductionsWebService.listarSeriesXNombreResponse retVal = ((SoftProductions.SoftProductionsWebService.SoftProductionsWS)(this)).listarSeriesXNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarSeriesXNombreResponse> SoftProductions.SoftProductionsWebService.SoftProductionsWS.listarSeriesXNombreAsync(SoftProductions.SoftProductionsWebService.listarSeriesXNombreRequest request) {
            return base.Channel.listarSeriesXNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarSeriesXNombreResponse> listarSeriesXNombreAsync(string nombre) {
            SoftProductions.SoftProductionsWebService.listarSeriesXNombreRequest inValue = new SoftProductions.SoftProductionsWebService.listarSeriesXNombreRequest();
            inValue.nombre = nombre;
            return ((SoftProductions.SoftProductionsWebService.SoftProductionsWS)(this)).listarSeriesXNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWebService.listarTodasProductorasResponse SoftProductions.SoftProductionsWebService.SoftProductionsWS.listarTodasProductoras(SoftProductions.SoftProductionsWebService.listarTodasProductorasRequest request) {
            return base.Channel.listarTodasProductoras(request);
        }
        
        public SoftProductions.SoftProductionsWebService.productora[] listarTodasProductoras() {
            SoftProductions.SoftProductionsWebService.listarTodasProductorasRequest inValue = new SoftProductions.SoftProductionsWebService.listarTodasProductorasRequest();
            SoftProductions.SoftProductionsWebService.listarTodasProductorasResponse retVal = ((SoftProductions.SoftProductionsWebService.SoftProductionsWS)(this)).listarTodasProductoras(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarTodasProductorasResponse> SoftProductions.SoftProductionsWebService.SoftProductionsWS.listarTodasProductorasAsync(SoftProductions.SoftProductionsWebService.listarTodasProductorasRequest request) {
            return base.Channel.listarTodasProductorasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarTodasProductorasResponse> listarTodasProductorasAsync() {
            SoftProductions.SoftProductionsWebService.listarTodasProductorasRequest inValue = new SoftProductions.SoftProductionsWebService.listarTodasProductorasRequest();
            return ((SoftProductions.SoftProductionsWebService.SoftProductionsWS)(this)).listarTodasProductorasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWebService.listarDirectoresXNombreResponse SoftProductions.SoftProductionsWebService.SoftProductionsWS.listarDirectoresXNombre(SoftProductions.SoftProductionsWebService.listarDirectoresXNombreRequest request) {
            return base.Channel.listarDirectoresXNombre(request);
        }
        
        public SoftProductions.SoftProductionsWebService.director[] listarDirectoresXNombre(string nombre) {
            SoftProductions.SoftProductionsWebService.listarDirectoresXNombreRequest inValue = new SoftProductions.SoftProductionsWebService.listarDirectoresXNombreRequest();
            inValue.nombre = nombre;
            SoftProductions.SoftProductionsWebService.listarDirectoresXNombreResponse retVal = ((SoftProductions.SoftProductionsWebService.SoftProductionsWS)(this)).listarDirectoresXNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarDirectoresXNombreResponse> SoftProductions.SoftProductionsWebService.SoftProductionsWS.listarDirectoresXNombreAsync(SoftProductions.SoftProductionsWebService.listarDirectoresXNombreRequest request) {
            return base.Channel.listarDirectoresXNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.listarDirectoresXNombreResponse> listarDirectoresXNombreAsync(string nombre) {
            SoftProductions.SoftProductionsWebService.listarDirectoresXNombreRequest inValue = new SoftProductions.SoftProductionsWebService.listarDirectoresXNombreRequest();
            inValue.nombre = nombre;
            return ((SoftProductions.SoftProductionsWebService.SoftProductionsWS)(this)).listarDirectoresXNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWebService.insertarSerieResponse SoftProductions.SoftProductionsWebService.SoftProductionsWS.insertarSerie(SoftProductions.SoftProductionsWebService.insertarSerieRequest request) {
            return base.Channel.insertarSerie(request);
        }
        
        public int insertarSerie(SoftProductions.SoftProductionsWebService.serieTelevision serie) {
            SoftProductions.SoftProductionsWebService.insertarSerieRequest inValue = new SoftProductions.SoftProductionsWebService.insertarSerieRequest();
            inValue.serie = serie;
            SoftProductions.SoftProductionsWebService.insertarSerieResponse retVal = ((SoftProductions.SoftProductionsWebService.SoftProductionsWS)(this)).insertarSerie(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.insertarSerieResponse> SoftProductions.SoftProductionsWebService.SoftProductionsWS.insertarSerieAsync(SoftProductions.SoftProductionsWebService.insertarSerieRequest request) {
            return base.Channel.insertarSerieAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWebService.insertarSerieResponse> insertarSerieAsync(SoftProductions.SoftProductionsWebService.serieTelevision serie) {
            SoftProductions.SoftProductionsWebService.insertarSerieRequest inValue = new SoftProductions.SoftProductionsWebService.insertarSerieRequest();
            inValue.serie = serie;
            return ((SoftProductions.SoftProductionsWebService.SoftProductionsWS)(this)).insertarSerieAsync(inValue);
        }
    }
}
